version: 2

models:
  - name: stg_smard_generation
    description: "Cleaned generation signals from raw SMARD data.
                NUCLEAR signal is coalesced to 0 for the end wind-down period 
                and excluded after retirement (2024-02-04 22:00 UTC)"
    columns:
      - name: timestamp
        description: "UTC timestamp of the hourly observation."
        tests:
          - not_null

      - name: signal_name
        description: "Name of the generation signal e.g. WIND_ONSHORE, SOLAR, NUCLEAR."
        tests: 
          - not_null
          - accepted_values:
              arguments:
                values: ['WIND_ONSHORE', 'WIND_OFFSHORE', 'SOLAR', 'BIOMASS', 'HYDROPOWER', 'PUMPED_STORAGE', 
                        'NATURAL_GAS', 'HARD_COAL', 'BROWN_COAL', 'NUCLEAR', 'OTHER_CONVENTIONAL', 'OTHER_RENEWABLE',
                        'TOTAL_CONSUMPTION', 'RESIDUAL_LOAD']

      - name: value
        description: "Generation output in MW. Always >= 0."
        tests:
          - not_null

      - name: unit
        description: "Unit of measurement. Always MW for generation signals."
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['MW']

  - name: stg_smard_prices
    description: "Cleaned prices of Deutschland and Luxemburg from raw SMARD data."
    columns:
      - name: timestamp
        description: "UTC timestamp of the hourly observation."
        tests:
          - not_null

      - name: signal_name
        description: "Name of the generation signal 'DE-LU' "
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['DE_LU']

      - name: value
        description: "Price. It could be negative."
        tests:
          - not_null

      - name: unit
        description: "Unit of measurement. Always EUR_MWH for generation signals."
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['EUR_MWH']

  - name: stg_smard_neighbour_prices
    description: "Cleaned prices of Deutschland's Neighbours from raw SMARD data."
    columns:
      - name: timestamp
        description: "UTC timestamp of the hourly observation."
        tests:
          - not_null

      - name: signal_name
        description: "Name of the generation signal e.g. 'AUSTRIA','FRANCE','NETHERLANDS','POLAND' "
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['AUSTRIA','FRANCE','NETHERLANDS','POLAND','SWITZERLAND','CZECHIA','DENMARK_1','DENMARK_2']

      - name: value
        description: "Price. It could be negative"
        tests:
          - not_null

      - name: unit
        description: "Unit of measurement. Always EUR_MWH for generation signals."
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['EUR_MWH']

  - name: stg_weather
    description: "Cleaned weather informations for the 4 regions chosed from 4 renewable energy regions."
    columns:
      - name: timestamp
        description: "UTC timestamp of the hourly observation."
        tests:
          - not_null

      - name: region
        description: "Name of the region from where weather infos collected"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["wind_region_brandenburg","wind_region_schleswig","solar_region_bavaria","solar_region_bawue"]

      - name: signal_name
        description: "Name of the weather signal e.g. 'wind_speed_100m', 'temperature_2m'"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["wind_speed_100m","wind_direction_100m","shortwave_radiation","cloud_cover","temperature_2m"] 

      - name: value
        description: "Weather infos like wind_speed, wind_direction, temperatur etc. It could be negative"
        tests:
          - not_null

      - name: unit
        description: "Unit of weather info."
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["%","°","°C","km/h","W/m²"]

